<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/maintenance/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Maintenance Banner plugin  |
 | Copyright (C) 2017, duk3luk3                                          |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels = array();
$labels['maintenanceBanner'] = 'Webmail is unavailable from $start to $end due to maintenance';
$labels['maintenanceBannerLight'] = 'Webmail may be sporadically unavailable between $start and $end due to maintenance';
$labels['preMaintenanceBanner'] = 'Webmail will be unavailable from $start to $end due to maintenance';
$labels['preMaintenanceBannerLight'] = 'Webmail may be unavailable from $start to $end due to maintenance';
$labels['postMaintenanceBanner'] = 'Webmail maintenance was undertaken from $start to $end. Please notify the administrators if you notice any problems.';

?>
