<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/maintenance/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Maintenance Banner plugin  |
 | Copyright (C) 2017, duk3luk3                                          |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/

$labels = array();
$labels['maintenanceBanner'] = 'Webmail is niet beschikbaar van $start tot $end vanwege onderhoud.';
$labels['maintenanceBannerLight'] = 'Webmail is tijdelijk minder goed bereikbaar tussen $start en $end vanwege onderhoud.';
$labels['preMaintenanceBanner'] = 'Webmail zal vanwege onderhoud niet beschikbaar zijn tussen $start en $end';
$labels['preMaintenanceBannerLight'] = 'Webmail zal tijdelijk minder goed bereikbaar zijn tussen $start en $end vanwege onderhoud.';
$labels['postMaintenanceBanner'] = 'We hebben onderhoud uitgevoerd aan de webmail tussen $start en $end. Neem a.u.b. contact op als u problemen opmerkt.';

?>
